# Required : Main cost fonction to be displayed
[function1]
Groove={t = 0.0, d = 2, c = 0.1, f = 10.0, g = 2}

# Optional 
[function2]
Swamp={l_bound= -0.1, u_bound= 0.1, f1= 2.0, f2= 0.2, p1= 20}

# Optional 
[function3]
SwampGroove={g= 0.0, l_bound= -0.1, u_bound= 0.1, c= 0.2, f1= 1.0, f2= 0.01, f3= 2.0, p1= 20}

# Optional
[graph_options]
# title Default = name of toml file 
title= "Example graph"
# x_zone Default = [-0.5, 0.5]
x_zone= [-0.4, 0.4]
# y_zone Default = [-0.5, 0.5]
y_zone= [-1.1, 6.0]
# nb_points Default = 200
nb_points= 1000
# Default = [1920, 1080]
graph_size = [1280, 720]